# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v3
        
    - name: Run Python app
      run: python main.py > output.txt

    # - name: Display App ID
    #   run: echo "My APP_ID value is ${{ vars.APP_ID }}" > appid.txt

    # - name: Copy Server App
    #   run: cp server.py /home/wijamw/pyproject/server.py
