name: Cancel deploy on timeout

on:
  workflow_dispatch:

jobs:
  timeout:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Monitor deployment for timeout and cancel if crossed the threshold
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          sleep 1m
          gh -R wijamw/check-port run list -w python-app.yml -s queued --json databaseId -q .[].databaseId | xargs gh -R wijamw/check-port run cancel
